### ISSUE TITLE
Issue with Photon firmware v. 4.2.17

### ISSUE THREAD

**Issue by MakerMatrix** [Photonsters/FW_Tools#1]
Just d/l this to give it a try.  Had this issue - see attached screenshots. First I get the not a valid color offset, then the exception.

![Screenshot 2019-06-23 21 33 26](https://user-images.githubusercontent.com/52144433/59987222-8ad62580-95ff-11e9-98c6-bfd6c365d080.png)
![Screenshot 2019-06-23 21 33 33](https://user-images.githubusercontent.com/52144433/59987223-8b6ebc00-95ff-11e9-8ee4-d5e4f8391f7c.png)

**Comment by Cex123** [comment]
Need to fix the application to avoid raising an exception if the color in the FW is not really a color.
Until then I fixed the root of the problem that was an incorrect value in FWdata.csv file.

**Comment by MakerMatrix** [comment]
Thanks for the quick fix!  I'm able to customize now.  However there are still some things mixed up with 4.2.17 in the Dialog Colors.  For example, "Button Color" actually controls the text color on buttons, dialog messages, and the filename shown along with the model preview after selecting a file to print, It also appears to control the text color of the status area (time elapsed, time remaining, etc). 

Conversely, "Text Color" appears to control the dialog box background.

"Background" appears to control nothing, or at least I didn't trigger anything that took on that color.  I also appear to be unable to affect the button color - it's just white or a very light gray.

Even so, being able to customize has made a big improvement.  Thanks for your work on this!
![IMG_0935](https://user-images.githubusercontent.com/52144433/60001628-752b2500-962c-11e9-8c6a-1caf6cfb7375.jpg)
![IMG_0934](https://user-images.githubusercontent.com/52144433/60001629-752b2500-962c-11e9-99f0-6591b4c2da2e.jpg)

**Comment by Cex123** [comment]
Fixed again the FWdata.csv file. Sorry for the inconvenience. this time it should work as expected (still pending the application fix to avoid exception if something is wrong with the read colors.

**Comment by Cex123** [comment]
Fixed the application and the FWdata.csv.

**Comment by MakerMatrix** [comment]
All is well now, thank you very much!  This tool makes the printer so much better to use.

![colors](https://user-images.githubusercontent.com/52144433/60145867-0ca78980-978d-11e9-9bda-8a631bfa4a8c.jpg)
